get:
  operationId: getMotionAreaConfiguration
  summary: Get motion area configuration.
  description: Get details of a single motion area configuration resource from its given `{motionAreaConfigurationId}`.
  tags:
    - MotionAreaConfiguration
  security:
    - HueApplicationKey: [ ]
  parameters:
    - name: motionAreaConfigurationId
      in: path
      schema:
        type: string
      required: true
      description: ID of the motion area configuration
  responses:
    200:
      description: MotionAreaConfiguration Success Response
      content:
        application/json:
          schema:
            allOf:
              - $ref: '../common/ApiResponse.yaml'
              - type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: './schemas/MotionAreaConfigurationGet.yaml'
    401:
      $ref: '../common/error.yaml#/components/responses/Unauthorized'
    403:
      $ref: '../common/error.yaml#/components/responses/Forbidden'
    404:
      $ref: '../common/error.yaml#/components/responses/NotFound'
    405:
      $ref: '../common/error.yaml#/components/responses/MethodNotAllowed'
    406:
      $ref: '../common/error.yaml#/components/responses/NotAcceptable'
    409:
      $ref: '../common/error.yaml#/components/responses/Conflict'
    429:
      $ref: '../common/error.yaml#/components/responses/TooManyRequests'
    500:
      $ref: '../common/error.yaml#/components/responses/InternalServerError'
    503:
      $ref: '../common/error.yaml#/components/responses/ServiceUnavailable'
    507:
      $ref: '../common/error.yaml#/components/responses/InsufficientStorage'
put:
  operationId: updateMotionAreaConfiguration
  summary: Update motion area configuration.
  description: Update a single motion area configuration resource from its given `{motionAreaConfigurationId}`.
  tags:
    - MotionAreaConfiguration
  security:
    - HueApplicationKey: [ ]
  parameters:
    - name: motionAreaConfigurationId
      in: path
      schema:
        type: string
      required: true
      description: ID of the motion area configuration
  requestBody:
    content:
      application/json:
        schema:
          $ref: './schemas/MotionAreaConfigurationPut.yaml'
  responses:
    200:
      description: Success
      content:
        application/json:
          schema:
            allOf:
              - $ref: '../common/ApiResponse.yaml'
              - type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '../common/ResourceIdentifier.yaml'
    401:
      $ref: '../common/error.yaml#/components/responses/Unauthorized'
    403:
      $ref: '../common/error.yaml#/components/responses/Forbidden'
    404:
      $ref: '../common/error.yaml#/components/responses/NotFound'
    405:
      $ref: '../common/error.yaml#/components/responses/MethodNotAllowed'
    406:
      $ref: '../common/error.yaml#/components/responses/NotAcceptable'
    409:
      $ref: '../common/error.yaml#/components/responses/Conflict'
    429:
      $ref: '../common/error.yaml#/components/responses/TooManyRequests'
    500:
      $ref: '../common/error.yaml#/components/responses/InternalServerError'
    503:
      $ref: '../common/error.yaml#/components/responses/ServiceUnavailable'
    507:
      $ref: '../common/error.yaml#/components/responses/InsufficientStorage'
