get:
  operationId: getEntertainmentConfigurations
  summary: List entertainment configuration.
  description: List all available entertainment configuration resources.
  tags:
    - EntertainmentConfiguration
  security:
    - HueApplicationKey: [ ]
  responses:
    200:
      description: EntertainmentConfiguration Success Response
      content:
        application/json:
          schema:
            allOf:
              - $ref: '../common/ApiResponse.yaml'
              - type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: './schemas/EntertainmentConfigurationGet.yaml'
    401:
      $ref: '../common/error.yaml#/components/responses/Unauthorized'
    403:
      $ref: '../common/error.yaml#/components/responses/Forbidden'
    404:
      $ref: '../common/error.yaml#/components/responses/NotFound'
    405:
      $ref: '../common/error.yaml#/components/responses/MethodNotAllowed'
    406:
      $ref: '../common/error.yaml#/components/responses/NotAcceptable'
    409:
      $ref: '../common/error.yaml#/components/responses/Conflict'
    429:
      $ref: '../common/error.yaml#/components/responses/TooManyRequests'
    500:
      $ref: '../common/error.yaml#/components/responses/InternalServerError'
    503:
      $ref: '../common/error.yaml#/components/responses/ServiceUnavailable'
    507:
      $ref: '../common/error.yaml#/components/responses/InsufficientStorage'
